import os
import re
from urllib.parse import quote_plus

import requests

from nlp_engine.analysis.concepts import extract_concepts
from nlp_engine.analysis.topics import extract_topics

YOUTUBE_API_KEY = os.getenv("YOUTUBE_API_KEY", "")
YOUTUBE_SEARCH_URL = "https://www.googleapis.com/youtube/v3/search"
YOUTUBE_VIDEOS_URL = "https://www.googleapis.com/youtube/v3/videos"

# Fixed, real reference links. These are NOT generated by an LLM — Groq was
# previously asked to invent official-looking URLs for this section, which
# risked hallucinated/broken links. A small curated list is more reliable.
_GENERIC_REFERENCES = [
    {
        "title": "NCERT ePathshala Digital Textbook & Audio",
        "type": "Official Portal",
        "description": "Official Ministry of Education portal for chapter audiobooks, flipbooks, and resources.",
        "source": "epathshala.nic.in",
        "url": "https://epathshala.nic.in/",
    },
    {
        "title": "DIKSHA Educational Repository",
        "type": "Interactive Simulation",
        "description": "Interactive question banks, visual aids, and teacher-curated modules.",
        "source": "diksha.gov.in",
        "url": "https://diksha.gov.in/",
    },
    {
        "title": "NCERT Official Textbooks & Solutions",
        "type": "Study Notes",
        "description": "Download or read the official NCERT textbook chapter and related resources.",
        "source": "ncert.nic.in",
        "url": "https://ncert.nic.in/textbook.php",
    },
]


def _iso8601_to_mmss(duration: str) -> str:
    """Convert a YouTube ISO-8601 duration (e.g. 'PT12M45S') into 'MM:SS'."""
    if not duration:
        return ""
    match = re.match(r"PT(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?", duration)
    if not match:
        return ""
    hours, minutes, seconds = (int(g) if g else 0 for g in match.groups())
    minutes += hours * 60
    if hours:
        return f"{hours}:{minutes % 60:02d}:{seconds:02d}"
    return f"{minutes}:{seconds:02d}"


def _search_youtube(query: str, max_results: int = 1) -> list[dict]:
    """
    Looks up REAL videos via the YouTube Data API v3.
    Returns [] if no API key is configured, or the request/parse fails —
    callers must fall back to an honest 'suggested search' entry rather than
    inventing a title, channel, or duration.
    """
    if not YOUTUBE_API_KEY:
        return []

    try:
        search_resp = requests.get(
            YOUTUBE_SEARCH_URL,
            params={
                "key": YOUTUBE_API_KEY,
                "q": query,
                "part": "snippet",
                "type": "video",
                "maxResults": max_results,
                "safeSearch": "strict",
                "relevanceLanguage": "en",
                "videoEmbeddable": "true",
            },
            timeout=6,
        )
        search_resp.raise_for_status()
        items = search_resp.json().get("items", [])
        video_ids = [item["id"]["videoId"] for item in items if item.get("id", {}).get("videoId")]
        if not video_ids:
            return []

        durations = {}
        try:
            details_resp = requests.get(
                YOUTUBE_VIDEOS_URL,
                params={
                    "key": YOUTUBE_API_KEY,
                    "id": ",".join(video_ids),
                    "part": "contentDetails",
                },
                timeout=6,
            )
            details_resp.raise_for_status()
            for d in details_resp.json().get("items", []):
                durations[d["id"]] = _iso8601_to_mmss(
                    d.get("contentDetails", {}).get("duration", "")
                )
        except Exception:
            pass  # duration is a nice-to-have, never block on it

        results = []
        for item in items:
            vid = item.get("id", {}).get("videoId")
            if not vid:
                continue
            snippet = item.get("snippet", {})
            results.append({
                "video_id": vid,
                "title": (snippet.get("title") or "").strip(),
                "channel": (snippet.get("channelTitle") or "").strip(),
                "description": (snippet.get("description") or "")[:180].strip(),
                "thumbnail": (snippet.get("thumbnails", {}).get("medium") or {}).get("url", ""),
                "duration": durations.get(vid, ""),
                "url": f"https://www.youtube.com/watch?v={vid}",
                "verified": True,
            })
        return results
    except Exception as e:
        print(f"[Recommendations] YouTube API lookup failed: {e}")
        return []


def _suggested_search_entry(query: str, concept: str) -> dict:
    """
    Honest fallback used when no YOUTUBE_API_KEY is set, or a lookup fails.
    Clearly labeled as a search suggestion, not a specific recommended video.
    """
    return {
        "title": f"Search: {query}",
        "channel": "",
        "description": (
            f"No verified video lookup is configured, so this opens a YouTube "
            f"search for '{concept}' instead of a specific recommended video."
        ),
        "concept_tag": concept,
        "duration": "",
        "type": "Suggested Search",
        "search_query": query,
        "url": f"https://www.youtube.com/results?search_query={quote_plus(query)}",
        "verified": False,
    }


def recommend_educational_resources(
    chapter_title: str,
    chapter_text: str,
    subject: str = "General",
    class_level: str = "12",
    top_n_concepts: int = 5,
) -> dict:
    """
    Identifies core concepts/topics from the chapter using the existing NLP
    extraction (concepts.py / topics.py) — not an LLM guess — then looks up
    REAL videos for each concept via the YouTube Data API. If no API key is
    configured, or a lookup fails, returns a clearly-labeled 'Suggested
    Search' entry instead of a fabricated title/channel/duration.
    """
    if not chapter_text or not chapter_text.strip():
        return {
            "status": "error",
            "message": "Chapter text is empty.",
            "concepts_covered": [],
            "video_recommendations": [],
            "reference_resources": [],
        }

    concepts_raw = extract_concepts(chapter_text[:4000], top_n=top_n_concepts)
    concept_names = [c["concept"] if isinstance(c, dict) else str(c) for c in concepts_raw]

    if not concept_names:
        topics_raw = extract_topics(chapter_text[:4000], num_topics=3)
        for t in topics_raw:
            if isinstance(t, dict) and t.get("words"):
                concept_names.extend(t["words"][:2])

    if not concept_names:
        concept_names = [chapter_title]

    top_concepts = concept_names[:top_n_concepts] or [chapter_title]

    video_recommendations = []
    for concept in top_concepts[:4]:
        query = f"NCERT Class {class_level} {subject} {chapter_title} {concept} explanation"
        real_videos = _search_youtube(query, max_results=1)
        if real_videos:
            for v in real_videos:
                v["concept_tag"] = concept
                v["type"] = "YouTube Video"
                video_recommendations.append(v)
        else:
            video_recommendations.append(_suggested_search_entry(query, concept))

    return {
        "status": "success",
        "chapter_title": chapter_title,
        "concepts_covered": top_concepts,
        "video_recommendations": video_recommendations,
        "reference_resources": _GENERIC_REFERENCES,
    }